/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poo;

/**
 *
 * @author gerar
 */
public class PanelCarga extends javax.swing.JPanel
{

    /**
     * Creates new form PanelCarga
     */
    public PanelCarga()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 245, 248));
        setMaximumSize(new java.awt.Dimension(930, 556));
        setMinimumSize(new java.awt.Dimension(930, 556));
        setPreferredSize(new java.awt.Dimension(930, 556));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(243, 245, 248));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carga.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(930, 556));
        jLabel1.setMinimumSize(new java.awt.Dimension(930, 556));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(930, 470));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 160, 320));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cargando...");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 410, 80));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
