/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poo;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Inspiron 15
 */
public final class PnlGrupos extends javax.swing.JPanel
{

    /**
     * Creates new form VtnregistroGrupos
     */
    public PnlGrupos()
    {
        initComponents();

        if (!VtnPrincipal.m.lleno())
        {
            llenarTabla();
        }
    }

    public int extraerNumeroDia()
    {
        int dia = 1;
        int n = cmBoxDia.getSelectedIndex();
        for (DiasSemana value : DiasSemana.values())
        {
            if (n == value.ordinal())
            {
                System.out.println("El dia es: " + (n + 1));
                System.out.println("Dia: " + value.name());
                dia = n + 1;
            }
        }
        return dia;
    }

    public char extraerTipoGrupo()
    {
        char tipo = 'I';
        int n = cmBoxTipoGrupo.getSelectedIndex();
        for (TipoGrupo value : TipoGrupo.values())
        {
            if (n == value.ordinal())
            {
                System.out.println("El tipo es: " + value.name());
                if (n == 0)
                {
                    tipo = 'I';
                } else
                {
                    tipo = 'A';
                }
            }
        }
        System.out.println(tipo);
        return tipo;
    }

    public void llenarTabla()
    {
        String d = "";
        String tipo;
        DefaultTableModel modelodefault = new DefaultTableModel(new String[]
        {
            "Dia", "Hora", "Tipo", "Clave"
        }, VtnPrincipal.m.arreglo.size());
        tablaGrupos.setModel(modelodefault);

        TableModel modeloDatos = tablaGrupos.getModel();
        for (int i = 0; i < VtnPrincipal.m.arreglo.size(); i++)
        {
            Grupos grupo = VtnPrincipal.m.arreglo.get(i);
            for (DiasSemana value : DiasSemana.values())
            {
                if (grupo.dia == (value.ordinal() + 1))
                {
                    d = value.name();
                }
            }
            if (grupo.tipo == 'I')
            {
                tipo = TipoGrupo.Infante.name();
            } else
            {
                tipo = TipoGrupo.Adulto.name();
            }
            modeloDatos.setValueAt(d, i, 0);//los setvalue corresponden a la cantidad de datos por fila
            modeloDatos.setValueAt(grupo.hora, i, 1);
            modeloDatos.setValueAt(tipo, i, 2);
            modeloDatos.setValueAt(grupo.clave, i, 3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelRedondo1 = new pnlsConsulta.PanelRedondo();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaHora = new javax.swing.JTextField();
        texth = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaClave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmBoxDia = new javax.swing.JComboBox<>();
        cmBoxTipoGrupo = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGrupos = new javax.swing.JTable();
        btnElimina = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelRedondo1.setBackground(new java.awt.Color(247, 245, 230));
        panelRedondo1.setRoundBottomLeft(50);
        panelRedondo1.setRoundBottomRight(50);
        panelRedondo1.setRoundTopLeft(50);
        panelRedondo1.setRoundTopRight(50);

        jPanel1.setBackground(new java.awt.Color(247, 245, 230));

        jLabel1.setText("Dia:");

        texth.setText("Hora");

        jLabel3.setText("Tipo");

        cajaClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cajaClaveKeyTyped(evt);
            }
        });

        jLabel4.setText("Clave");

        cmBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.- Domingo", "2.- Lunes", "3.- Martes", "4.- Miercoles", "5.- Jueves", "6.- Viernes", "7.- Sabado" }));
        cmBoxDia.setBorder(null);
        cmBoxDia.setOpaque(true);
        cmBoxDia.setBackground(Color.white);
        cmBoxDia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmBoxDiaActionPerformed(evt);
            }
        });

        cmBoxTipoGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I: Infante", "A: Adulto" }));
        cmBoxTipoGrupo.setBorder(null);
        cmBoxTipoGrupo.setOpaque(true);
        cmBoxTipoGrupo.setBackground(Color.white);
        cmBoxTipoGrupo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmBoxTipoGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(texth, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1))
                            .addGap(36, 36, 36))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(39, 39, 39)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmBoxDia, 0, 199, Short.MAX_VALUE)
                            .addComponent(cajaHora))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmBoxTipoGrupo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cajaClave))
                        .addGap(9, 9, 9))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texth)
                    .addComponent(cajaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmBoxTipoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cajaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnAceptarMouseClicked(evt);
            }
        });

        jLabel5.setText("Aceptar");

        javax.swing.GroupLayout btnAceptarLayout = new javax.swing.GroupLayout(btnAceptar);
        btnAceptar.setLayout(btnAceptarLayout);
        btnAceptarLayout.setHorizontalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAceptarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btnAceptarLayout.setVerticalGroup(
            btnAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAceptarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnCancelarMouseClicked(evt);
            }
        });

        jLabel6.setText("Cancelar");

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        tablaGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Dia", "Hora", "Tipo", "Clave"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaGrupos);

        btnElimina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElimina.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnEliminaMouseClicked(evt);
            }
        });

        jLabel7.setText("Eliminar");

        javax.swing.GroupLayout btnEliminaLayout = new javax.swing.GroupLayout(btnElimina);
        btnElimina.setLayout(btnEliminaLayout);
        btnEliminaLayout.setHorizontalGroup(
            btnEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEliminaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnEliminaLayout.setVerticalGroup(
            btnEliminaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Agregar grupo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Grupos actuales");

        javax.swing.GroupLayout panelRedondo1Layout = new javax.swing.GroupLayout(panelRedondo1);
        panelRedondo1.setLayout(panelRedondo1Layout);
        panelRedondo1Layout.setHorizontalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
            .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondo1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo1Layout.createSequentialGroup()
                            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRedondo1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelRedondo1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRedondo1Layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(266, 266, 266))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                            .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(33, 33, 33)))
        );
        panelRedondo1Layout.setVerticalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRedondo1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8))
                    .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRedondo1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelRedondo1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnElimina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnAceptarMouseClicked
    {//GEN-HEADEREND:event_btnAceptarMouseClicked
        if (VtnPrincipal.validaCajasnoVacias(cajaHora, cajaClave))
        {
            if (VtnPrincipal.m.verificaClaveItf(cajaClave.getText()))
            {
                VtnPrincipal.m.insertaGrupo(new Grupos(extraerNumeroDia(), cajaHora.getText(),
                        extraerTipoGrupo(), cajaClave.getText()));
                JOptionPane.showMessageDialog(null, "registro exitoso");
                btnCancelarMouseClicked(evt);
                llenarTabla();
                VtnPrincipal.m.guarda();
            } else
            {
                JOptionPane.showMessageDialog(null, "clave registro en uso");
                CtrlInterfaz.cambia(cajaClave);
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "llena todos los espacios");
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCancelarMouseClicked
    {//GEN-HEADEREND:event_btnCancelarMouseClicked
        CtrlInterfaz.limpia(cajaClave, cajaHora);
        cmBoxDia.setSelectedIndex(0);
        cmBoxTipoGrupo.setSelectedIndex(0);
        CtrlInterfaz.cambia(cmBoxDia);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEliminaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnEliminaMouseClicked
    {//GEN-HEADEREND:event_btnEliminaMouseClicked
        int n = JOptionPane.showConfirmDialog(this, "Esta seguro(eliminara los alumnos en el grupo)",
                "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (n == JOptionPane.YES_OPTION)
        {
            int dato = tablaGrupos.getSelectedRow();
            if (dato >= 0)
            {
                VtnPrincipal.m.arreglo.remove(dato);
                VtnPrincipal.m.matriz.remove(dato);
                llenarTabla();
                VtnPrincipal.m.guarda();
            } else
            {
                JOptionPane.showMessageDialog(null, "seleccione el grupo a eliminar");
            }
        }

    }//GEN-LAST:event_btnEliminaMouseClicked

    private void cmBoxDiaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmBoxDiaActionPerformed
    {//GEN-HEADEREND:event_cmBoxDiaActionPerformed
        extraerNumeroDia();
    }//GEN-LAST:event_cmBoxDiaActionPerformed

    private void cmBoxTipoGrupoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmBoxTipoGrupoActionPerformed
    {//GEN-HEADEREND:event_cmBoxTipoGrupoActionPerformed
        extraerTipoGrupo();
    }//GEN-LAST:event_cmBoxTipoGrupoActionPerformed

    private void cajaClaveKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cajaClaveKeyTyped
    {//GEN-HEADEREND:event_cajaClaveKeyTyped
        Validaciones.validaAlfanumerico(evt, 10, cajaClave.getText());
    }//GEN-LAST:event_cajaClaveKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAceptar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnElimina;
    private javax.swing.JTextField cajaClave;
    private javax.swing.JTextField cajaHora;
    private javax.swing.JComboBox<String> cmBoxDia;
    private javax.swing.JComboBox<String> cmBoxTipoGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private pnlsConsulta.PanelRedondo panelRedondo1;
    private javax.swing.JTable tablaGrupos;
    private javax.swing.JLabel texth;
    // End of variables declaration//GEN-END:variables
}
