/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.text.html.CSS;

/**
 *
 * @author gerar
 */
public class VtnAdmin2 extends javax.swing.JFrame {

    boolean b = false;
    boolean banderAzul = false;
    boolean banderAzul1 = false;
    boolean banderAzul2 = false;

    /**
     * Creates new form VtnGruposAlumnos
     */
    public VtnAdmin2() {
        initComponents();
    }
    public void showP(JPanel p){
         p.setSize(870, 420);
        p.setLocation(0, 0);
        contentP.removeAll();
        contentP.add(p,BorderLayout.CENTER);
        contentP.revalidate();
        contentP.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelRaiz = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        pnlVista = new javax.swing.JPanel();
        lblVista = new javax.swing.JLabel();
        pnlAlumnos = new javax.swing.JPanel();
        lblAlumnos = new javax.swing.JLabel();
        pnlGrupos = new javax.swing.JPanel();
        lbGrupos = new javax.swing.JLabel();
        contentP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administración");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        panelRaiz.setBackground(new java.awt.Color(255, 255, 255));
        panelRaiz.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                panelRaizMouseClicked(evt);
            }
        });
        panelRaiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVista.setBackground(new java.awt.Color(255, 255, 255));
        pnlVista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlVista.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                pnlVistaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                pnlVistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                pnlVistaMouseExited(evt);
            }
        });
        pnlVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVista.setBackground(new java.awt.Color(255, 255, 255));
        lblVista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVista.setText("Vista...");
        lblVista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVista.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblVistaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblVistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblVistaMouseExited(evt);
            }
        });
        pnlVista.add(lblVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 80, 40));

        pnlMenu.add(pnlVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 310, 40));

        pnlAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        pnlAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAlumnos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                pnlAlumnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                pnlAlumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                pnlAlumnosMouseExited(evt);
            }
        });
        pnlAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        lblAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumnos.setText("Alumnos");
        lblAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAlumnos.setPreferredSize(new java.awt.Dimension(34, 16));
        lblAlumnos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblAlumnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblAlumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblAlumnosMouseExited(evt);
            }
        });
        pnlAlumnos.add(lblAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 40));

        pnlMenu.add(pnlAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 310, 40));

        pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
        pnlGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGrupos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                pnlGruposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                pnlGruposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                pnlGruposMouseExited(evt);
            }
        });
        pnlGrupos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbGrupos.setBackground(new java.awt.Color(0, 153, 255));
        lbGrupos.setForeground(new java.awt.Color(255, 255, 255));
        lbGrupos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGrupos.setText("Grupos");
        lbGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbGrupos.setPreferredSize(new java.awt.Dimension(34, 16));
        lbGrupos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lbGruposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lbGruposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lbGruposMouseExited(evt);
            }
        });
        pnlGrupos.add(lbGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 40));

        pnlMenu.add(pnlGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 40));

        panelRaiz.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 40));

        contentP.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPLayout = new javax.swing.GroupLayout(contentP);
        contentP.setLayout(contentPLayout);
        contentPLayout.setHorizontalGroup(
            contentPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        contentPLayout.setVerticalGroup(
            contentPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        panelRaiz.add(contentP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 930, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRaiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        //lblTitulo.setText("Administración");
    }//GEN-LAST:event_formWindowOpened

    private void lbGruposMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lbGruposMouseExited
    {//GEN-HEADEREND:event_lbGruposMouseExited
        if (banderAzul1 == false) {

        } else {
            pnlGrupos.setBackground(Color.white);
        }

    }//GEN-LAST:event_lbGruposMouseExited

    private void lblVistaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVistaMouseClicked
    {//GEN-HEADEREND:event_lblVistaMouseClicked
        if (b == false) {
            pnlGrupos.setBackground(Color.white);
            lbGrupos.setForeground(Color.black);
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
            lblVista.setForeground(Color.white);
          
            b = true;
            banderAzul = true;
            banderAzul1 = true;
            //banderAzul2 = true;
        } else {
            pnlVista.setBackground(Color.white);
            lblVista.setForeground(Color.black);
           
            b = false;
            banderAzul = false;
            banderAzul1 = false;
            //banderAzul2 = false;
            if (!banderAzul1) {
                pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
                lbGrupos.setForeground(Color.white);
            }
        }
    }//GEN-LAST:event_lblVistaMouseClicked

    private void panelRaizMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelRaizMouseClicked
    {//GEN-HEADEREND:event_panelRaizMouseClicked
        pnlVista.setBackground(Color.white);
        lblVista.setForeground(Color.black);
      
        b = false;
        banderAzul = false;
        banderAzul1 = false;
        if (!banderAzul1) {
            pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
            lbGrupos.setForeground(Color.white);
        }
    }//GEN-LAST:event_panelRaizMouseClicked

    private void lblVistaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVistaMouseEntered
    {//GEN-HEADEREND:event_lblVistaMouseEntered
        if (banderAzul == true) {
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlVista.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_lblVistaMouseEntered

    private void lblVistaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVistaMouseExited
    {//GEN-HEADEREND:event_lblVistaMouseExited

        if (banderAzul == true) {
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlVista.setBackground(Color.white);
        }
    }//GEN-LAST:event_lblVistaMouseExited

    private void lblAlumnosMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblAlumnosMouseEntered
    {//GEN-HEADEREND:event_lblAlumnosMouseEntered
        if (banderAzul2 == true) {

            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlAlumnos.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_lblAlumnosMouseEntered

    private void lblAlumnosMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblAlumnosMouseExited
    {//GEN-HEADEREND:event_lblAlumnosMouseExited
        if (banderAzul2 == true) {
            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlAlumnos.setBackground(Color.white);
        }
    }//GEN-LAST:event_lblAlumnosMouseExited

    private void pnlGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseClicked
        pnlVista.setBackground(Color.white);
        lblVista.setForeground(Color.black);
      
        b = false;
        banderAzul = false;
        banderAzul1 = false;
        if (!banderAzul1) {
            pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
            lbGrupos.setForeground(Color.white);
        }
       VtnregistroGrupos vtg =new VtnregistroGrupos();
        showP(vtg);
    }//GEN-LAST:event_pnlGruposMouseClicked

    private void pnlGruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseEntered
        if (banderAzul1 == false) {

        } else {
            pnlGrupos.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_pnlGruposMouseEntered

    private void lbGruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGruposMouseEntered
        if (banderAzul1 == false) {

        } else {
            pnlGrupos.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_lbGruposMouseEntered

    private void lbGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbGruposMouseClicked
        pnlVista.setBackground(Color.white);
        lblVista.setForeground(Color.black);
      
        b = false;
        banderAzul = false;
        banderAzul1 = false;
        if (!banderAzul1) {
            pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
            lbGrupos.setForeground(Color.white);
        }
    }//GEN-LAST:event_lbGruposMouseClicked

    private void pnlGruposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGruposMouseExited
        if (banderAzul1 == false) {

        } else {
            pnlGrupos.setBackground(Color.white);
        }
    }//GEN-LAST:event_pnlGruposMouseExited

    private void pnlVistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVistaMouseClicked
        if (b == false) {
            pnlGrupos.setBackground(Color.white);
            lbGrupos.setForeground(Color.black);
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
            lblVista.setForeground(Color.white);
          
            b = true;
            banderAzul = true;
            banderAzul1 = true;
            
        } else {
            pnlVista.setBackground(Color.white);
            lblVista.setForeground(Color.black);
           
            b = false;
            banderAzul = false;
            banderAzul1 = false;
            
            if (!banderAzul1) {
                pnlGrupos.setBackground(new java.awt.Color(0, 153, 255));
                lbGrupos.setForeground(Color.white);
            }
        }
    }//GEN-LAST:event_pnlVistaMouseClicked

    private void pnlVistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVistaMouseEntered
        if (banderAzul == true) {
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlVista.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_pnlVistaMouseEntered

    private void pnlVistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVistaMouseExited
        if (banderAzul == true) {
            pnlVista.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlVista.setBackground(Color.white);
        }
    }//GEN-LAST:event_pnlVistaMouseExited

    private void pnlAlumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnosMouseEntered
        if (banderAzul2 == true) {

            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlAlumnos.setBackground(new java.awt.Color(242, 242, 242));
        }
    }//GEN-LAST:event_pnlAlumnosMouseEntered

    private void pnlAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnosMouseClicked
        pnlVista.setBackground(Color.white);
        lblVista.setForeground(Color.black);
        pnlGrupos.setBackground(Color.white);
        lbGrupos.setForeground(Color.black);
     
        b = false;
        banderAzul = false;
        banderAzul1 = false;
        banderAzul2 = false;
        if (!banderAzul2) {
            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
            lblAlumnos.setForeground(Color.white);
        }
    }//GEN-LAST:event_pnlAlumnosMouseClicked

    private void lblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlumnosMouseClicked
        pnlVista.setBackground(Color.white);
        lblVista.setForeground(Color.black);
        pnlGrupos.setBackground(Color.white);
        lbGrupos.setForeground(Color.black);
     
        b = false;
        banderAzul = false;
        banderAzul1 = false;
        banderAzul2 = false;
        if (!banderAzul2 ) {
            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
            lblAlumnos.setForeground(Color.white);
        }
    }//GEN-LAST:event_lblAlumnosMouseClicked

    private void pnlAlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAlumnosMouseExited
        if (banderAzul2 == true) {
            pnlAlumnos.setBackground(new java.awt.Color(0, 153, 255));
        } else {
            pnlAlumnos.setBackground(Color.white);
        }
    }//GEN-LAST:event_pnlAlumnosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAdmin2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAdmin2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentP;
    private javax.swing.JLabel lbGrupos;
    private javax.swing.JLabel lblAlumnos;
    private javax.swing.JLabel lblVista;
    private javax.swing.JPanel panelRaiz;
    private javax.swing.JPanel pnlAlumnos;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlVista;
    // End of variables declaration//GEN-END:variables
}
