/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.BorderLayout;
import java.awt.Color;
import pnlsConsulta.VtnConsulta;
import pnlsRegistro.VtnRegistroAlumno;

/**
 *
 * @author sebasgil
 */
public class VtnRegistro extends javax.swing.JFrame
{

    private Color colorOriginalJPanel3;
    private Color colorOriginalJPanel4;
    private Color colorOriginalJPanel5;

    /**
     * Creates new form VtnRegistro
     */
    public VtnRegistro()
    {
        initComponents();
//
//        VtnRegistroAlumno llamadoRegistro = new VtnRegistroAlumno();
//        llamadoRegistro.setSize(759, 478);
//        llamadoRegistro.setLocation(0, 0);
//
//        contenido.removeAll();
//        contenido.add(llamadoRegistro,BorderLayout.CENTER);
//        contenido.revalidate();
//        contenido.repaint();
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelRaiz = new javax.swing.JPanel();
        pnlMenuRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonRegistrarAlum = new javax.swing.JPanel();
        iconRegistro1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonConsultarAlum = new javax.swing.JPanel();
        iconBusqueda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonSalida = new javax.swing.JPanel();
        iconSalida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlEncabezadoRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");

        panelRaiz.setBackground(new java.awt.Color(255, 255, 255));
        panelRaiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuRegistro.setBackground(new java.awt.Color(0, 197, 152));
        pnlMenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Natación icono 96.png"))); // NOI18N
        jLabel2.setText("Nom Escuela");
        pnlMenuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-circulo-110.png"))); // NOI18N
        pnlMenuRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        botonRegistrarAlum.setBackground(new java.awt.Color(18, 179, 171));
        botonRegistrarAlum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarAlum.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseExited(evt);
            }
        });

        iconRegistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-añadir-usuario-masculino-64.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar alumno");

        javax.swing.GroupLayout botonRegistrarAlumLayout = new javax.swing.GroupLayout(botonRegistrarAlum);
        botonRegistrarAlum.setLayout(botonRegistrarAlumLayout);
        botonRegistrarAlumLayout.setHorizontalGroup(
            botonRegistrarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarAlumLayout.createSequentialGroup()
                .addComponent(iconRegistro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonRegistrarAlumLayout.setVerticalGroup(
            botonRegistrarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconRegistro1)
            .addGroup(botonRegistrarAlumLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3))
        );

        pnlMenuRegistro.add(botonRegistrarAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, -1));

        botonConsultarAlum.setBackground(new java.awt.Color(18, 179, 171));
        botonConsultarAlum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarAlum.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseExited(evt);
            }
        });

        iconBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Icono búsqueda 50.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultar alumno");

        javax.swing.GroupLayout botonConsultarAlumLayout = new javax.swing.GroupLayout(botonConsultarAlum);
        botonConsultarAlum.setLayout(botonConsultarAlumLayout);
        botonConsultarAlumLayout.setHorizontalGroup(
            botonConsultarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        botonConsultarAlumLayout.setVerticalGroup(
            botonConsultarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                .addGroup(botonConsultarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconBusqueda))
                    .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuRegistro.add(botonConsultarAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        botonSalida.setBackground(new java.awt.Color(18, 179, 171));
        botonSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseExited(evt);
            }
        });

        iconSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Salida 50.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Salir");

        javax.swing.GroupLayout botonSalidaLayout = new javax.swing.GroupLayout(botonSalida);
        botonSalida.setLayout(botonSalidaLayout);
        botonSalidaLayout.setHorizontalGroup(
            botonSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSalidaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonSalidaLayout.setVerticalGroup(
            botonSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botonSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSalida)
                    .addGroup(botonSalidaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuRegistro.add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, -1));

        panelRaiz.add(pnlMenuRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 705));

        pnlEncabezadoRegistro.setBackground(new java.awt.Color(13, 169, 217));

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        jLabel1.setText("Sistema de registro y consulta");

        javax.swing.GroupLayout pnlEncabezadoRegistroLayout = new javax.swing.GroupLayout(pnlEncabezadoRegistro);
        pnlEncabezadoRegistro.setLayout(pnlEncabezadoRegistroLayout);
        pnlEncabezadoRegistroLayout.setHorizontalGroup(
            pnlEncabezadoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoRegistroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        pnlEncabezadoRegistroLayout.setVerticalGroup(
            pnlEncabezadoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoRegistroLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        panelRaiz.add(pnlEncabezadoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 0, 780, 120));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        panelRaiz.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 120, 770, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarAlumMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseEntered
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseEntered
        colorOriginalJPanel3 = botonRegistrarAlum.getBackground();
        botonRegistrarAlum.setBackground(colorOriginalJPanel3.darker());
    }//GEN-LAST:event_botonRegistrarAlumMouseEntered

    private void botonRegistrarAlumMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseExited
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseExited
        botonRegistrarAlum.setBackground(colorOriginalJPanel3);
    }//GEN-LAST:event_botonRegistrarAlumMouseExited

    private void botonConsultarAlumMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseEntered
    {//GEN-HEADEREND:event_botonConsultarAlumMouseEntered
        colorOriginalJPanel4 = botonConsultarAlum.getBackground();
        botonConsultarAlum.setBackground(colorOriginalJPanel4.darker());
    }//GEN-LAST:event_botonConsultarAlumMouseEntered

    private void botonConsultarAlumMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseExited
    {//GEN-HEADEREND:event_botonConsultarAlumMouseExited
        botonConsultarAlum.setBackground(colorOriginalJPanel4);
    }//GEN-LAST:event_botonConsultarAlumMouseExited

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseEntered
    {//GEN-HEADEREND:event_botonSalidaMouseEntered
        colorOriginalJPanel5 = botonSalida.getBackground();
        botonSalida.setBackground(colorOriginalJPanel5.darker());
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void botonSalidaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseExited
    {//GEN-HEADEREND:event_botonSalidaMouseExited
       botonSalida.setBackground(colorOriginalJPanel5);

    }//GEN-LAST:event_botonSalidaMouseExited

    private void botonRegistrarAlumMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseClicked
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseClicked
        VtnRegistroAlumno llamadoRegistro = new VtnRegistroAlumno();
        llamadoRegistro.setSize(759, 478);
        llamadoRegistro.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(llamadoRegistro, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
//        new VtnRegistroAlumno().setVisible(true);
    }//GEN-LAST:event_botonRegistrarAlumMouseClicked

    private void botonSalidaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseClicked
    {//GEN-HEADEREND:event_botonSalidaMouseClicked
        this.dispose();
    }//GEN-LAST:event_botonSalidaMouseClicked

    private void botonConsultarAlumMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseClicked
    {//GEN-HEADEREND:event_botonConsultarAlumMouseClicked
        VtnConsulta llamadoConsulta = new VtnConsulta();
        llamadoConsulta.setSize(759, 478);
        llamadoConsulta.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(llamadoConsulta, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
//        new VtnRegistroAlumno().setVisible(true);
    }//GEN-LAST:event_botonConsultarAlumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonConsultarAlum;
    private javax.swing.JPanel botonRegistrarAlum;
    private javax.swing.JPanel botonSalida;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel iconBusqueda;
    private javax.swing.JLabel iconRegistro1;
    private javax.swing.JLabel iconSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelRaiz;
    private javax.swing.JPanel pnlEncabezadoRegistro;
    private javax.swing.JPanel pnlMenuRegistro;
    // End of variables declaration//GEN-END:variables
}
