/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import pnlsConsulta.VtnConsulta;
import pnlsRegistro.VtnRegistroAlumno;

/**
 *
 * @author sebasgil
 */
public class VtnRegistro extends javax.swing.JFrame
{

    private Color colorOriginalJPanel3;
    private Color colorOriginalJPanel4;
    private Color colorOriginalJPanel5;

    private ImageIcon imagen;
    private Icon icono;

    /**
     * Creates new form VtnRegistro
     */
    public VtnRegistro()
    {
        initComponents();
//
//        VtnRegistroAlumno llamadoRegistro = new VtnRegistroAlumno();
//        llamadoRegistro.setSize(759, 478);
//        llamadoRegistro.setLocation(0, 0);
//
//        contenido.removeAll();
//        contenido.add(llamadoRegistro,BorderLayout.CENTER);
//        contenido.revalidate();
//        contenido.repaint();
        this.setLocationRelativeTo(null);

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelRaiz = new javax.swing.JPanel();
        pnlMenuRegistro = new javax.swing.JPanel();
        botonRegistrarAlum = new javax.swing.JPanel();
        tituloBotonReg = new javax.swing.JLabel();
        iconBtnReg = new javax.swing.JLabel();
        botonConsultarAlum = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        iconBusqueda = new javax.swing.JLabel();
        botonSalida = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        iconSalida = new javax.swing.JLabel();
        encabezadoPanelMenu = new javax.swing.JLabel();
        tituloBotonReg2 = new javax.swing.JLabel();
        tituloBotonReg1 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");

        panelRaiz.setBackground(new java.awt.Color(255, 255, 255));
        panelRaiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuRegistro.setBackground(new java.awt.Color(51, 58, 86));
        pnlMenuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonRegistrarAlum.setBackground(new java.awt.Color(82, 101, 143));
        botonRegistrarAlum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistrarAlum.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonRegistrarAlumMouseExited(evt);
            }
        });

        tituloBotonReg.setBackground(new java.awt.Color(255, 255, 255));
        tituloBotonReg.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        tituloBotonReg.setForeground(new java.awt.Color(232, 232, 232));
        tituloBotonReg.setText("Registrar alumno");

        iconBtnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Añadir usuario masculino 30.png"))); // NOI18N

        javax.swing.GroupLayout botonRegistrarAlumLayout = new javax.swing.GroupLayout(botonRegistrarAlum);
        botonRegistrarAlum.setLayout(botonRegistrarAlumLayout);
        botonRegistrarAlumLayout.setHorizontalGroup(
            botonRegistrarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconBtnReg, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(tituloBotonReg)
                .addGap(16, 16, 16))
        );
        botonRegistrarAlumLayout.setVerticalGroup(
            botonRegistrarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonRegistrarAlumLayout.createSequentialGroup()
                .addGroup(botonRegistrarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconBtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(botonRegistrarAlumLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tituloBotonReg)))
                .addGap(15, 15, 15))
        );

        pnlMenuRegistro.add(botonRegistrarAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 50));

        botonConsultarAlum.setBackground(new java.awt.Color(82, 101, 143));
        botonConsultarAlum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConsultarAlum.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonConsultarAlumMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 232, 232));
        jLabel4.setText("Consultar alumno");

        iconBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iconos búsqueda 30.png"))); // NOI18N

        javax.swing.GroupLayout botonConsultarAlumLayout = new javax.swing.GroupLayout(botonConsultarAlum);
        botonConsultarAlum.setLayout(botonConsultarAlumLayout);
        botonConsultarAlumLayout.setHorizontalGroup(
            botonConsultarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
        );
        botonConsultarAlumLayout.setVerticalGroup(
            botonConsultarAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                .addComponent(iconBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(botonConsultarAlumLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenuRegistro.add(botonConsultarAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 200, 50));

        botonSalida.setBackground(new java.awt.Color(82, 101, 143));
        botonSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalida.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonSalidaMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Kailasa", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(232, 232, 232));
        jLabel5.setText("Salir");

        iconSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Salida 30 (1).png"))); // NOI18N

        javax.swing.GroupLayout botonSalidaLayout = new javax.swing.GroupLayout(botonSalida);
        botonSalida.setLayout(botonSalidaLayout);
        botonSalidaLayout.setHorizontalGroup(
            botonSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconSalida)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        botonSalidaLayout.setVerticalGroup(
            botonSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(botonSalidaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlMenuRegistro.add(botonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 50));

        encabezadoPanelMenu.setBackground(new java.awt.Color(247, 245, 230));
        encabezadoPanelMenu.setFont(new java.awt.Font("Kailasa", 1, 18)); // NOI18N
        encabezadoPanelMenu.setForeground(new java.awt.Color(247, 245, 230));
        encabezadoPanelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Natación icono 100.png"))); // NOI18N
        pnlMenuRegistro.add(encabezadoPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 80));

        tituloBotonReg2.setBackground(new java.awt.Color(255, 255, 255));
        tituloBotonReg2.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        tituloBotonReg2.setForeground(new java.awt.Color(232, 232, 232));
        tituloBotonReg2.setText("Natación");
        pnlMenuRegistro.add(tituloBotonReg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        tituloBotonReg1.setBackground(new java.awt.Color(255, 255, 255));
        tituloBotonReg1.setFont(new java.awt.Font("Charter", 1, 18)); // NOI18N
        tituloBotonReg1.setForeground(new java.awt.Color(232, 232, 232));
        tituloBotonReg1.setText("TEC");
        pnlMenuRegistro.add(tituloBotonReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        panelRaiz.add(pnlMenuRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 620));

        contenido.setBackground(new java.awt.Color(187, 187, 187));
        contenido.setMinimumSize(new java.awt.Dimension(780, 620));
        contenido.setRequestFocusEnabled(false);

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        panelRaiz.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistrarAlumMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseEntered
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseEntered
        colorOriginalJPanel3 = botonRegistrarAlum.getBackground();
        botonRegistrarAlum.setBackground(colorOriginalJPanel3.darker());
    }//GEN-LAST:event_botonRegistrarAlumMouseEntered

    private void botonRegistrarAlumMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseExited
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseExited
        botonRegistrarAlum.setBackground(colorOriginalJPanel3);
    }//GEN-LAST:event_botonRegistrarAlumMouseExited

    private void botonConsultarAlumMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseEntered
    {//GEN-HEADEREND:event_botonConsultarAlumMouseEntered
        colorOriginalJPanel4 = botonConsultarAlum.getBackground();
        botonConsultarAlum.setBackground(colorOriginalJPanel4.darker());
    }//GEN-LAST:event_botonConsultarAlumMouseEntered

    private void botonConsultarAlumMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseExited
    {//GEN-HEADEREND:event_botonConsultarAlumMouseExited
        botonConsultarAlum.setBackground(colorOriginalJPanel4);
    }//GEN-LAST:event_botonConsultarAlumMouseExited

    private void botonSalidaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseEntered
    {//GEN-HEADEREND:event_botonSalidaMouseEntered
        colorOriginalJPanel5 = botonSalida.getBackground();
        botonSalida.setBackground(colorOriginalJPanel5.darker());
    }//GEN-LAST:event_botonSalidaMouseEntered

    private void botonSalidaMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseExited
    {//GEN-HEADEREND:event_botonSalidaMouseExited
        botonSalida.setBackground(colorOriginalJPanel5);

    }//GEN-LAST:event_botonSalidaMouseExited

    private void botonRegistrarAlumMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonRegistrarAlumMouseClicked
    {//GEN-HEADEREND:event_botonRegistrarAlumMouseClicked
        VtnRegistroAlumno llamadoRegistro = new VtnRegistroAlumno();
        llamadoRegistro.setSize(780, 620);
        llamadoRegistro.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(llamadoRegistro, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
//        new VtnRegistroAlumno().setVisible(true);
    }//GEN-LAST:event_botonRegistrarAlumMouseClicked

    private void botonSalidaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonSalidaMouseClicked
    {//GEN-HEADEREND:event_botonSalidaMouseClicked
        this.dispose();
    }//GEN-LAST:event_botonSalidaMouseClicked

    private void botonConsultarAlumMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonConsultarAlumMouseClicked
    {//GEN-HEADEREND:event_botonConsultarAlumMouseClicked
        VtnConsulta llamadoConsulta = new VtnConsulta();
        llamadoConsulta.setSize(820, 520);
        llamadoConsulta.setLocation(0, 0);

        contenido.removeAll();
        contenido.add(llamadoConsulta, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
//        new VtnRegistroAlumno().setVisible(true);
    }//GEN-LAST:event_botonConsultarAlumMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistro().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonConsultarAlum;
    private javax.swing.JPanel botonRegistrarAlum;
    private javax.swing.JPanel botonSalida;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel encabezadoPanelMenu;
    private javax.swing.JLabel iconBtnReg;
    private javax.swing.JLabel iconBusqueda;
    private javax.swing.JLabel iconSalida;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelRaiz;
    private javax.swing.JPanel pnlMenuRegistro;
    private javax.swing.JLabel tituloBotonReg;
    private javax.swing.JLabel tituloBotonReg1;
    private javax.swing.JLabel tituloBotonReg2;
    // End of variables declaration//GEN-END:variables
}
