/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pnlsConsulta;

import java.awt.Color;

/**
 *
 * @author sebasgil
 */
public class VtnError extends javax.swing.JPanel
{
    
    private Color colorOriginalBtn;
    /**
     * Creates new form VtnError
     */
    public VtnError()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        raizError = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonAceptarError = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        raizError.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icons8-error-240.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¡Alumno no encontrado!");

        botonAceptarError.setBackground(new java.awt.Color(255, 0, 51));
        botonAceptarError.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonAceptarError.setToolTipText("");
        botonAceptarError.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonAceptarErrorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                botonAceptarErrorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                botonAceptarErrorMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aceptar");

        javax.swing.GroupLayout botonAceptarErrorLayout = new javax.swing.GroupLayout(botonAceptarError);
        botonAceptarError.setLayout(botonAceptarErrorLayout);
        botonAceptarErrorLayout.setHorizontalGroup(
            botonAceptarErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonAceptarErrorLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        botonAceptarErrorLayout.setVerticalGroup(
            botonAceptarErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonAceptarErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout raizErrorLayout = new javax.swing.GroupLayout(raizError);
        raizError.setLayout(raizErrorLayout);
        raizErrorLayout.setHorizontalGroup(
            raizErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, raizErrorLayout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
            .addGroup(raizErrorLayout.createSequentialGroup()
                .addGroup(raizErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(raizErrorLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(raizErrorLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(botonAceptarError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        raizErrorLayout.setVerticalGroup(
            raizErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raizErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(botonAceptarError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(raizError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(raizError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarErrorMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonAceptarErrorMouseClicked
    {//GEN-HEADEREND:event_botonAceptarErrorMouseClicked
//       this.dispose();
    }//GEN-LAST:event_botonAceptarErrorMouseClicked

    private void botonAceptarErrorMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonAceptarErrorMouseEntered
    {//GEN-HEADEREND:event_botonAceptarErrorMouseEntered
        colorOriginalBtn = botonAceptarError.getBackground();
        botonAceptarError.setBackground(colorOriginalBtn.darker());
    }//GEN-LAST:event_botonAceptarErrorMouseEntered

    private void botonAceptarErrorMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_botonAceptarErrorMouseExited
    {//GEN-HEADEREND:event_botonAceptarErrorMouseExited
        botonAceptarError.setBackground(colorOriginalBtn);
    }//GEN-LAST:event_botonAceptarErrorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAceptarError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel raizError;
    // End of variables declaration//GEN-END:variables
}
