/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pnlsRegistro;

import java.awt.BorderLayout;

/**
 *
 * @author sebasgil
 */
public class VtnRegistroAlum extends javax.swing.JFrame
{

    /**
     * Creates new form VtnRegistroAlum
     */
    public VtnRegistroAlum()
    {
        initComponents();
        
        /**
         * Para mostrar cada panel correspondiente, se instancia un objeto de cada clase 
         */
        VtnRegistroExternos RegExter = new VtnRegistroExternos();
        RegExter.setSize(878,446);
        RegExter.setLocation(0,0);
        
        contenidoRegistros.removeAll();
        contenidoRegistros.add(RegExter, BorderLayout.CENTER);
        contenidoRegistros.revalidate();
        contenidoRegistros.repaint();
                

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlRaiz = new javax.swing.JPanel();
        btnInternos = new javax.swing.JButton();
        btnExternos = new javax.swing.JButton();
        contenidoRegistros = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));

        pnlRaiz.setBackground(new java.awt.Color(255, 255, 255));

        btnInternos.setText("Interno");
        btnInternos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnInternosActionPerformed(evt);
            }
        });

        btnExternos.setText("Externo");
        btnExternos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExternosActionPerformed(evt);
            }
        });

        contenidoRegistros.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoRegistrosLayout = new javax.swing.GroupLayout(contenidoRegistros);
        contenidoRegistros.setLayout(contenidoRegistrosLayout);
        contenidoRegistrosLayout.setHorizontalGroup(
            contenidoRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        contenidoRegistrosLayout.setVerticalGroup(
            contenidoRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlRaizLayout = new javax.swing.GroupLayout(pnlRaiz);
        pnlRaiz.setLayout(pnlRaizLayout);
        pnlRaizLayout.setHorizontalGroup(
            pnlRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRaizLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnInternos, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(58, 58, 58)
                .addComponent(btnExternos, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(176, 176, 176))
            .addGroup(pnlRaizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenidoRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRaizLayout.setVerticalGroup(
            pnlRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRaizLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExternos, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btnInternos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInternosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnInternosActionPerformed
    {//GEN-HEADEREND:event_btnInternosActionPerformed
       VtnRegistroInternos RegInter = new VtnRegistroInternos();
        RegInter.setSize(878,446);
        RegInter.setLocation(0,0);
        
        contenidoRegistros.removeAll();
        contenidoRegistros.add(RegInter, BorderLayout.CENTER);
        contenidoRegistros.revalidate();
        contenidoRegistros.repaint(); 
    }//GEN-LAST:event_btnInternosActionPerformed

    private void btnExternosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnExternosActionPerformed
    {//GEN-HEADEREND:event_btnExternosActionPerformed
       VtnRegistroExternos RegExter = new VtnRegistroExternos();
        RegExter.setSize(878,446);
        RegExter.setLocation(0,0);
        
        contenidoRegistros.removeAll();
        contenidoRegistros.add(RegExter, BorderLayout.CENTER);
        contenidoRegistros.revalidate();
        contenidoRegistros.repaint();
    }//GEN-LAST:event_btnExternosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistroAlum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistroAlum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExternos;
    private javax.swing.JButton btnInternos;
    private javax.swing.JPanel contenidoRegistros;
    private javax.swing.JPanel pnlRaiz;
    // End of variables declaration//GEN-END:variables
}
